name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  image_picker: ^1.1.1
  geolocator: ^14.0.2
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1

  rename: ^3.1.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.12
  permission_handler: ^12.0.1
  intl: ^0.20.2
  speech_to_text: ^7.3.0
  flutter_tts: ^4.0.2
  connectivity_plus: ^6.0.3
  google_mlkit_image_labeling: ^0.12.0
  geocoding: ^2.2.0
  http: ^1.2.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/images/
    - .env
